demo1: demo1.chpl
	chpl -o demo1 demo1.chpl

demo2: demo2.chpl
	chpl -o demo2 demo2.chpl

demo3: demo3.chpl
	chpl -o demo3 demo3.chpl

demo4: demo4.chpl
	chpl -o demo4 demo4.chpl

exercise1: exercise1.chpl
	chpl -o exercise1 exercise1.chpl

exercise2: exercise2.chpl
	chpl -o exercise2 exercise2.chpl

exercise3: exercise3.chpl
	chpl -o exercise3 exercise3.chpl

exercise4: exercise4.chpl
	chpl -o exercise4 --fast exercise4.chpl

solution1: solution1.chpl
	chpl -o solution1 solution1.chpl

solution2: solution2.chpl
	chpl -o solution2 solution2.chpl

solution3: solution3.chpl
	chpl -o solution3 solution3.chpl

clean:
	rm -f demo1 demo2 demo3 demo4 exercise1 exercise2 exercise3 exercise4 *_real solution1 solution2 solution3
